test reorg

diff --git a/src/test b/src/test
--- a/src/test
+++ b/src/test
@@ -1,12 +1,26 @@
 #!/bin/bash
 
-for file in ../tests/strobe/*.sb
+for file in ../tests/strobe-typable/*.sb
 do
   echo -en "\r\e[KTest $file ... "
-  # echo -en "Test $file ... "
   result=`../tc -env $file.env -sb $file 2>&1`
   if [ $? -ne 0 ]; then
       echo -e "$file: aborted with exit code $?; output was:\n$result\n"
+  fi
+done
+
+for file in ../tests/strobe-untypable/*.sb
+do
+  echo -en "\r\e[KTest $file ... "
+  result=`../tc -env $file.env -sb $file 2>&1`
+  exitcode=$?
+  if [ $exitcode -ne 2 ]; then
+      echo -e "$file: expected a type-error error; exit code was $exitcode\n"
+      continue
+  fi
+  errors=`echo "$result" | grep -ci "type error"`
+  if [ $errors -ne 1 ]; then
+    echo -e "$file: expected a type error error; got\n$result\n"
   fi
 done
 
