test now tests everything. added separate browser folder for tests that need browser stuff. moved gadgets that need a lot of work, like their xml files to be parsed etc, to tmp folder . made array contracts work on eberything

diff --git a/src/test b/src/test
--- a/src/test
+++ b/src/test
@@ -2,7 +2,7 @@
 
 for file in ../tests/not-well-formed/*.js
 do
-  result=`../build/main.d.byte -env ../data/javascript.env -pretc $file 2>&1`
+  result=`../tc -pretc $file 2>&1`
   exitcode=$?
   if [ $exitcode -ne 2 ]; then
       echo "$file: expected a well-formedness error; exit code was $exitcode\n"
@@ -16,7 +16,7 @@ done
 
 for file in ../tests/well-formed/*.js
 do
-  result=`../build/main.d.byte -env ../data/javascript.env -pretc $file 2>&1`
+  result=`../tc -pretc $file 2>&1`
   if [ $? -ne 0 ]; then
       echo "$file: aborted with exit code $?; output was:\n$result\n"
   fi
@@ -25,7 +25,7 @@ done
 
 for file in ../tests/untypable/*.js
 do
-  result=`../build/main.d.byte -env ../data/javascript.env -tc $file 2>&1`
+  result=`../tc -tc $file 2>&1`
   exitcode=$?
   if [ $exitcode -ne 2 ]; then
       echo "$file: expected a type-error error; exit code was $exitcode\n"
@@ -39,7 +39,15 @@ done
 
 for file in ../tests/typable/*.js
 do
-  result=`../build/main.d.byte -env ../data/javascript.env -tc $file 2>&1`
+  result=`../tc -tc $file 2>&1`
+  if [ $? -ne 0 ]; then
+      echo "$file: aborted with exit code $?; output was:\n$result\n"
+  fi
+done
+
+for file in ../tests/browser/*.js
+do
+  result=`../tcb -tc $file 2>&1`
   if [ $? -ne 0 ]; then
       echo "$file: aborted with exit code $?; output was:\n$result\n"
   fi
@@ -48,7 +56,7 @@ done
 
 for file in ../tests/parsing/*.js
 do
-  result=`../build/main.d.byte -env ../data/javascript.env -pretty $file 2>&1`
+  result=`../tc -pretty $file 2>&1`
   if [ $? -ne 0 ]; then
       echo "$file: aborted with exit code $?; output was:\n$result\n"
   fi
@@ -60,3 +68,5 @@ do
   ./runtest.sh $FILE
 done
 
+cd ../gadgets
+./test
