update tests to call strobe tests

diff --git a/src/test b/src/test
--- a/src/test
+++ b/src/test
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+for file in ../tests/strobe/*.sb
+do
+  echo -en "\r\e[KTest $file ... "
+  # echo -en "Test $file ... "
+  result=`../tc -env $file.env -sb $file 2>&1`
+  if [ $? -ne 0 ]; then
+      echo -e "$file: aborted with exit code $?; output was:\n$result\n"
+  fi
+done
+
 for file in ../tests/regex/*.txt
 do
     echo "Test ../tests/gadgets/$file ... "
