well-formedness

diff --git a/src/test b/src/test
--- a/src/test
+++ b/src/test
@@ -1,5 +1,5 @@
 #!/bin/sh
 for file in ../tests/*.txt
 do
-  ../build/main.d.byte -unittest $file
+  ../build/main.d.byte -unittest $file || echo "ERROR on $file"
 done
