Environment in a file.

diff --git a/src/test b/src/test
--- a/src/test
+++ b/src/test
@@ -1,13 +1,13 @@
 #!/bin/sh
 for file in ../tests/*.txt
 do
-  ../build/main.d.byte -unittest $file || echo "ERROR on $file"
+  ../build/main.d.byte -env ../data/env -unittest $file || echo "ERROR on $file"
 done
 
 
 for file in ../tests/not-well-formed/*.js
 do
-  result=`../build/main.d.byte -pretc $file 2>&1`
+  result=`../build/main.d.byte -env ../data/env -pretc $file 2>&1`
   exitcode=$?
   if [ $exitcode -ne 2 ]; then
       echo "$file: expected a well-formedness error; exit code was $exitcode\n"
@@ -21,7 +21,7 @@ done
 
 for file in ../tests/well-formed/*.js
 do
-  result=`../build/main.d.byte -pretc $file 2>&1`
+  result=`../build/main.d.byte -env ../data/env -pretc $file 2>&1`
   if [ $? -ne 0 ]; then
       echo "$file: aborted with exit code $?; output was:\n$result\n"
   fi
@@ -30,7 +30,7 @@ done
 
 for file in ../tests/untypable/*.js
 do
-  result=`../build/main.d.byte -tc $file 2>&1`
+  result=`../build/main.d.byte -env ../data/env -tc $file 2>&1`
   exitcode=$?
   if [ $exitcode -ne 2 ]; then
       echo "$file: expected a type-error error; exit code was $exitcode\n"
@@ -39,5 +39,13 @@ do
   errors=`echo "$result" | grep -ci "type error"`
   if [ $errors -ne 1 ]; then
     echo "$file: expected a type error error; got\n$result\n"
+  fi
+done
+
+for file in ../tests/typable/*.js
+do
+  result=`../build/main.d.byte -env ../data/env -tc $file 2>&1`
+  if [ $? -ne 0 ]; then
+      echo "$file: aborted with exit code $?; output was:\n$result\n"
   fi
 done
